---
services:
  docker-obsidian-livesync:
      container_name: obsidian-livesync #shortened name
      image: couchdb:3.3.3
      environment:
        - PUID=99
        - PGID=100
        - UMASK=0022
        - TZ=America/New_York
        - COUCHDB_USER=obsidian_user # optionally change me, must update init script
        - COUCHDB_PASSWORD=password # definitly change me, must update init script
      ports:
        - "5984:5984"
      volumes:
        - ./appdata/livesync/data:/opt/couchdb/data
        - ./appdata/livesync/etc/local.d:/opt/couchdb/etc/local.d
      restart: unless-stopped
